-- Legacy schema snapshot intentionally retired.
--
-- The authoritative database schema is maintained by SQLAlchemy models in
-- src/models.py and Alembic migrations in migrations/versions/.
--
-- To create or upgrade a database, run:
--
--     alembic upgrade head
--
-- Keeping a hand-written schema copy here caused drift from the real app
-- schema, including user/profile tables, review uniqueness, and current
-- index definitions.
